# Inserts a blank line between shell prompts
add_newline = false

[git_branch]
format = 'on [$branch(:$remote_branch)]($style) '

[git_status]
format = ''

[container]
format = '[$symbol ]($style) '

[battery]
full_symbol = '󰁹 '
charging_symbol = '󰂄 '
discharging_symbol = '󰂃 '
unknown_symbol = '󰁽 '
empty_symbol = '󰂎 '

[[battery.display]]
threshold = 20
style = 'bold red'
